# Form implementation generated from reading ui file 'principal.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import Clases


class Ui_Herramientas(object):
    def funcionDescompresora(self):
        desc = Clases.Descompresion_ZIP()
        desc.descompresion()

    def funcionConversora(self):
        conv = Clases.Conversion_XML()
        conv.conversion()

    def funcionQueUneMuchosArchivosExcel(self):
        union = Clases.Unir_archivos()
        union.unir_archivos()

    def setupUi(self, Herramientas):
        Herramientas.setObjectName("Herramientas")
        Herramientas.resize(516, 324)
        self.centralwidget = QtWidgets.QWidget(Herramientas)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_descomprimir = QtWidgets.QPushButton(self.centralwidget)
        self.btn_descomprimir.setGeometry(QtCore.QRect(10, 10, 151, 121))
        self.btn_descomprimir.setObjectName("btn_descomprimir")
        # AGREGAGO DE LA FUNCION DESCOMPRIMIR
        self.btn_descomprimir.clicked.connect(self.funcionDescompresora)

        self.btn_convertir = QtWidgets.QPushButton(self.centralwidget)
        self.btn_convertir.setGeometry(QtCore.QRect(180, 10, 151, 121))
        self.btn_convertir.setObjectName("btn_convertir")
        # AGREGAGO DE LA FUNCION QUE CONVIERTE ARCHIVOS XML A EXCEL ESPECIFICAMENTE FACTURAS
        self.btn_convertir.clicked.connect(self.funcionConversora)

        self.btn_unir_archivos = QtWidgets.QPushButton(self.centralwidget)
        self.btn_unir_archivos.setGeometry(QtCore.QRect(350, 10, 151, 121))
        self.btn_unir_archivos.setObjectName("btn_unir_archivos")
        # AGREGAGO DE LA FUNCION QUE CONVIERTE ARCHIVOS XML A EXCEL ESPECIFICAMENTE FACTURAS
        self.btn_unir_archivos.clicked.connect(self.funcionQueUneMuchosArchivosExcel)

        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 180, 151, 91))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(180, 180, 151, 91))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(350, 180, 151, 91))
        self.textBrowser_3.setObjectName("textBrowser_3")
        Herramientas.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Herramientas)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 516, 21))
        self.menubar.setObjectName("menubar")
        Herramientas.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Herramientas)
        self.statusbar.setObjectName("statusbar")
        Herramientas.setStatusBar(self.statusbar)

        self.retranslateUi(Herramientas)
        QtCore.QMetaObject.connectSlotsByName(Herramientas)

    def retranslateUi(self, Herramientas):
        _translate = QtCore.QCoreApplication.translate
        Herramientas.setWindowTitle(_translate("Herramientas", "Herramientas"))
        self.btn_descomprimir.setText(_translate("Herramientas", "Descomprimir"))
        self.btn_convertir.setText(_translate("Herramientas", "Convertir XML - XLSX"))
        self.btn_unir_archivos.setText(_translate("Herramientas", "Unir varios Archivos Excel"))
        self.textBrowser.setHtml(_translate("Herramientas", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Los Archivos deben ser .ZIP y deben estar en la carpeta de ENTRADAS</p></body></html>"))
        self.textBrowser_2.setHtml(_translate("Herramientas", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Los archivos deben ser .XML y deben estar en la caperta SALIDAS</p></body></html>"))
        self.textBrowser_3.setHtml(_translate("Herramientas", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Los archivos a unir deben ser .XLSX y deben estar en la carpeta SALIDAS</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Herramientas = QtWidgets.QMainWindow()
    ui = Ui_Herramientas()
    ui.setupUi(Herramientas)
    Herramientas.show()
    sys.exit(app.exec())
